# Generated by Django 4.1.4 on 2022-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_parent_post_image_post_subtitle_post_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replyid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
